name: .5-SAST-Check-Pull-Request-or-Branch1

on:
  workflow_dispatch:
  
jobs:
  SAST-Check-Pull-Request-or-Branch:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3

    - name: Build App
      run: dotnet publish app/app.csproj -o ./publish

    - name: Zip Application Files 
      uses: vimtor/action-zip@v1
      with:
        files: publish/
        dest: ./publish.zip

    - name: Create results directory
      run: mkdir -p ./results

    - name: Download Veracode Static Pipeline Scanner
      run: |
        curl https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip -o veracode.zip
        unzip -o veracode.zip
  
    - name: Run Veracode Static Pipeline Scanner
      id: veracode_scan
      run: |
        java -jar pipeline-scan.jar -vid "${{ secrets.VERACODE_API_ID }}" -vkey "${{ secrets.VERACODE_API_KEY }}" -f publish.zip -sf ./results/results.txt -p VeraDemo-DotNetCore
        echo "Output:"
        cat ./results/results.txt || echo "Results file not found or empty."

    - name: List Results Directory
      run: |
        echo "Listing files in ./results:"
        ls -l ./results

    - name: Archive Results from Veracode Static Pipeline Scanner
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Pipeline Scanner Results
        path: |
          ./results/results.txt
